name: Deploy React app to GitHub Pages

on:
  push:
    branches:
      - master    # or whatever your default branch is

permissions:
  contents: read             # for checkout
  pages: write               # to deploy
  id-token: write            # for Pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm ci
      - run: npm run build

      - uses: actions/configure-pages@v3
        # No inputs needed here

      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./build

      - uses: actions/deploy-pages@v1
